// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CBO.Core.Orders.DataAccess.Csc.Entities
{
    public partial class Company
    {
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public int CompanyStatusId { get; set; }
        public string CompanyOIB { get; set; }
        public string CompanyEmail { get; set; }
        public int? CompanyAddressId { get; set; }
        public string CompanyOwnerName { get; set; }
        public string CompanyOwnerSurname { get; set; }
        public string CompanyMainContactPhoneNumber { get; set; }
        public DateTime? Created { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? LastUpd { get; set; }
        public string LastUpdBy { get; set; }
        public string LastUpdApp { get; set; }
    }
}