// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CBO.Core.Orders.DataAccess.Csc.Entities
{
    public partial class VehicleClass
    {
        public int VehicleClassId { get; set; }
        public string VehicleClassName { get; set; }
        public int? VehicleSeatNumber { get; set; }
        public DateTime? Created { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? LastUpd { get; set; }
        public string LastUpdBy { get; set; }
        public string LastUpdApp { get; set; }
    }
}